import pandas as pd
import os

def extract_intro_stats(input_csv):
    # Load the segregated data
    if not os.path.exists(input_csv):
        print(f"File {input_csv} not found.")
        return

    df = pd.read_csv(input_csv)
    
    # Define the columns we want to analyze
    target_cols = [
        'Trust_Overall', 'Extraversion', 'Agreeableness', 
        'Conscientiousness', 'Neuroticism', 'Openness', 'Culture_Affinity'
    ]
    
    # Calculate stats
    stats = df[target_cols].agg(['mean', 'std', 'var']).T
    stats.columns = ['Mean', 'Std', 'Var']
    
    # Generate LaTeX code
    print(f"\n--- Statistics for {input_csv} ---")
    print("\\begin{table}[ht]")
    print("\\centering")
    print("\\caption{Descriptive Statistics: " + input_csv.split('/')[-1] + "}")
    print("\\begin{tabular}{lccc}")
    print("\\toprule")
    print("Trait & Mean ($\mu$) & Std ($\sigma$) & Var ($\sigma^2$) \\\\")
    print("\\midrule")
    
    for trait, row in stats.iterrows():
        # Clean the trait name for LaTeX (removing underscores)
        trait_name = trait.replace('_', ' ')
        print(f"{trait_name} & {row['Mean']:.3f} & {row['Std']:.3f} & {row['Var']:.3f} \\\\")
        
    print("\\bottomrule")
    print("\\end{tabular}")
    print("\\end{table}")

if __name__ == "__main__":
    # You can run this for each file generated by the segregation script
    files = ['distinct/global_intro.csv', 'distinct/german_intro.csv', 'distinct/italian_intro.csv']
    
    for f in files:
        extract_intro_stats(f)