import pandas as pd
import os

def setup_distinct_directory():
    """Creates the target directory for subset data."""
    path = 'distinct'
    if not os.path.exists(path):
        os.makedirs(path)
    return path

def extract_condition_subsets(input_csv):
    """
    Partitions the interaction data into specific Nationality and Paradigm groups.
    """
    # Load the processed interaction features
    df = pd.read_csv(input_csv)
    
    target_dir = setup_distinct_directory()
    
    nationalities = df['Nationality'].unique()
    paradigms = df['Paradigm'].unique()
    
    # Selected features for external analysis
    features = ['Participant_ID', 'Culture_Closeness_Avg', 'Competence_Overall']

    # 1. Extraction by Nationality and Paradigm
    for nat in nationalities:
        for pad in paradigms:
            subset = df[(df['Nationality'] == nat) & (df['Paradigm'] == pad)]
            if not subset.empty:
                filename = f"{nat}_Paradigm_{pad}.csv"
                subset[features].to_csv(os.path.join(target_dir, filename), index=False)

    # 2. Extraction for Global Data (Combined Nationalities) by Paradigm
    for pad in paradigms:
        global_subset = df[df['Paradigm'] == pad]
        if not global_subset.empty:
            filename = f"Global_Paradigm_{pad}.csv"
            global_subset[features].to_csv(os.path.join(target_dir, filename), index=False)

if __name__ == "__main__":
    # Point to the interaction features generated by the previous pipeline
    source_file = 'golden_layer/interaction_features_full.csv'
    
    if os.path.exists(source_file):
        extract_condition_subsets(source_file)
        print(f"Extraction complete. Data partitions are located in the 'distinct/' folder.")
    else:
        print(f"Error: {source_file} not found. Please run the interaction analysis first.")